---
layout: post
title: Identifying spatial points within a Buffer of spatial objects
bibliography: bibliography.bib
tags: [R, spatial, ggplot2, rgeos]
categories: [R, spatial]
date: "`r format(Sys.time(), '%d %B, %Y')`"
---
<!--{% include JB/setup %} -->
 

---------------

Spatial discontinuity sometimes allows for a clean impact evaluation. For example, Balck (1999) made use of the fact that school districts strictly determine which school kids may enter to evaluate the value of school quality, reflected on the housing price.
Housing prices are heavily dependent on spatial heterogeneous characteristics, such as, crime rate and the distance to a park, etc. One way to control for these spatial variables that are sometimes unobservables (thus often cause omitted variable bias) is to compare houses that are very close to the border that separates one side from the other. In this post, I will show you how to identify spatial observation units (in this example, they are irrigation wells in Nebraska) that are within the buffer around such a border.

First, let's load packages we are going to use in this session.

```{r setup, message=FALSE, warning=FALSE}
library(rgdal)
library(data.table)
library(dplyr)
library(ggplot2)
library(rgeos)
```

```{r library, echo=FALSE, message=FALSE}
library(knitr)
opts_knit$set(root.dir = '~/Dropbox/tmieno2.github.com/data')
opts_chunk$set(fig.path='{{ site.url }}/images/buffer-',dpi=300)
```

<br />

Let's now import a data set of wells located within the Upper and Middle Republican Natural Resources Districts (URNRD and MRNRD, respectively). 

```{r wells, message=FALSE}
wells <- fread('wells_urmr.csv')
```

<br />

We also import a shape file of county boundaries for Nebraska and then subset it to have only Chase, Dundy, Perkins, Lincoln, Hayes, and Hitchcock County. We then give a status of "urnrd" to wells located within either one of Chase, Dundy, and Perkins County and "mrnrd" to the rest.

```{r county, message=FALSE}
NE_county <- readOGR(dsn = ".", "county_bound")
um_county <- NE_county[NE_county@data$COUNTY_NAM %in% c('CHASE', 'DUNDY', 'PERKINS','LINCOLN', 'HAYES', 'HITCHCOCK'),]
um_county@data$nrd <- 'mrnrd'
um_county@data[um_county@data$COUNTY_NAM %in% c('CHASE', 'DUNDY', 'PERKINS'),'nrd'] <- 'urnrd'
```

<br />

Here is the map of wells:

```{r worldmap}
um_county_f <- fortify(um_county,region = "COUNTY_NAM") %>% data.table()
g_wells <- ggplot(data=wells,aes(x=long,y=lat)) + 
	geom_point(colour='orange',size=0.7) +
	coord_equal(ratio=1) +
  	labs(x="", y="") + #labels
  	theme(
  		axis.ticks.y = element_blank(),
  		axis.text.y = element_blank(), # get rid of x ticks/text
  		axis.ticks.x = element_blank(),
  		axis.text.x = element_blank(),
  		panel.background = element_rect(fill='white')
  	)

g_with_bound <- g_wells + 
	geom_polygon(data=um_county_f,aes(x=long,y=lat,group=group),fill=NA,colour="black",size=0.5) 

g_with_bound
```

<br />

The objective here is to find wells that are close to the border that separates URNRD and MRNRD, which is the vertical (almost) line that separates all the counties into 3 to the west and 3 to the east. Since we are not interested in the horizontal borders, let's dissolve the URNRD and MRNRD counties individually using the **gUnaryUnion( )** function from the **rgeos** package.

```{r dissolve}
u_to_m <- gUnaryUnion(um_county, um_county@data$nrd)
```

<br />

Now the map looks like this:

```{r show1}
u_to_m_f <- fortify(u_to_m,region='nrd')
g_with_dis <- g_wells +
	geom_polygon(data=u_to_m_f,aes(x=long,y=lat,group=group),fill=NA,colour="black")
g_with_dis
```

<br />

Now, let's create buffers around the borders using the **gBuffer( )** function from the **rgeos** package. You can see the red lines that are off by "20000" from the border of URNRD and MRNRD.

```{r buffer}
buf_nrd <- gBuffer(u_to_m,width=20000,byid=TRUE)
plot(buf_nrd, border = "red")
plot(u_to_m, add = TRUE)
```
<br />

Finding the intersection of the two buffers (red-shaded region) using **gIntersection( )** gives us almost what we want. 

```{r buffer_int}
buf_int <- gIntersection(buf_nrd[1, ], buf_nrd[2, ]) 
plot(buf_nrd, border = "red")
plot(u_to_m, add = TRUE)
plot(buf_int, add = TRUE, col = "#FF000080")
```

<br />

The problem is of course that the intersection includes area that does not belong to either URNRD or MRNRD. So, let's cut out those regions.

```{r final}
buf <- gIntersection(buf_int, gUnaryUnion(u_to_m))
plot(buf_nrd, border = "red")
plot(u_to_m, add = TRUE)
plot(buf, add = TRUE, col = "#FF000080")
```

<br />

Great. So, we've successfully created the buffer we want. The next step is to identify spatial points (wells) that are located within the buffer. This can be achieved easily with the **over( )** function.

```{r over}
#--- create a SpatialPointsDataFrame of wells ---#
wells_spatial <- SpatialPointsDataFrame(coords=wells[,list(long,lat)], data=wells)

#--- same projection scheme ---#
proj4string(wells_spatial) <- buf@proj4string

#--- which wells in the buffer? ---#
within <- over(wells_spatial,buf)
id_within <- cbind(wells[,list(id)],within)[!is.na(within),id] 

#--- select wells that are within the buffer ---#
wells_within <- wells[id %in% id_within,]
```

<br />

Let's confirm if what we've done is correct by looking at a map:

```{r final_map}
buf_f <- fortify(buf) %>% data.table()
g_with_bound +
	geom_polygon(data=buf_f,aes(x=long,y=lat,group=group),fill="#FF000080",alpha=0.4) +
	geom_point(data=wells_within,aes(x=long,y=lat),colour='blue',size=0.7)
```

Looking good. This is it for this post. Enjoy!

<br />
<br />

### Session Information

---------------

```{r, echo=FALSE}
sessionInfo()
```

<br />
<br />

### References

---------------

<p><span id="black99">Black, S. E. (1999). Do better schools matter? Parental valuation of elementary education. <i>Quarterly Journal of Economics</i>, 577–599.</span></p>


