---
layout: post
title: Creating square grid dummy variables for regression analysis
bibliography: bibliography.bib
tags: [R, spatial, ggplot2, grid, over]
categories: [R, spatial]
date: "2 June, 2015"
---
<!--{% include JB/setup %} -->

---------------

In the course of my work on the estimation of the impacts of brownfields cleanup on housing prices in NY, I used 0.25- by 0.25-mile square grid fixed effects, which have a tighter control on unobservable neighbor characteristics than census tract fixed effects. The use of square grid fixed effects originate from Linn (2013). In this post, I will show you how I created the square grid dummy variables. Specifically, we'll learn to:

1. Create a raster layer consisting of square grids that covers five counties in NY: Bronx, Queens, Kings, New York, and Richmond.
	* identify how many miles one latitude and longitude degrees are, respectively
	* identify the bounding box 
	* identify the number of rows and columns of the final layer
	* create a SpatialGridDataFrame from scratch based on the information from the previous steps

2. Overlay point data (property locations) on the grids to identify which property belongs to which grid.

Let's first load the packages we are going to use in this session.

```{r setup, message=FALSE, warning=FALSE}
library(knitr)
library(rgdal)
library(data.table)
library(dplyr)
library(ggplot2)
library(raster)
```

```{r library, echo=FALSE, message=FALSE}
opts_knit$set(root.dir = '~/Dropbox/tmieno2.github.com/data')
opts_chunk$set(fig.path='{{ site.url }}/images/sq_grid-')
```

<br />

Now, we need to know the geographic extent of the three states in order to see how many miles one latitude and longitude degrees are, respectively. One latitude degree is similar in distance from the south to north end of the globe and is equivalent to 69 miles more or less. On the other hand, one latitude degree means a very different distance depending on where you are. One longitude degree is the longest at the equator and is about 69 miles. However, as you go farther away from the equator, one longitude degree means a smaller distance. So, if we would like to create square grids, we need to know the conversion rate at the geographic extent of our interest. You can find this information [here](http://www.csgnetwork.com/degreelenllavcalc.html). At latitude of 41, 1 latitude degree = 69.01 miles and 1 longitude degree = 52.28 miles. As we would like to create 0.25- by 0.25-mile square grids, the step sizes (distance between the centroids of adjacent grids) are the following:

```{r distance}
lat_step_size <-	1/69.01/4
lon_step_size <-	1/52.28/4
```

<br />

Now, let's import a NY county shape file (can be downloaded from [here](http://www.arcgis.com/home/item.html?id=7f4850fb7d18496ca6925f209d2d1275)) using **readOGR( )** that comes with the **rgdal** package. 

```{r readpoly, message=FALSE, warning=FALSE}
ny_state <- readOGR(dsn = ".", "NY_counties_clip")

```

<br />

We then generate a subset of the SpatialPolygonDataFrame to contain only Bronx, Queens, Kings, New York, and Richmond counties. 

```{r subset}
counties <- ny_state[ny_state@data$NAME %in% c('Bronx','Queens','Kings','New York','Richmond'),]
```

<br />

To get the spatial extent of these counties, we can extract this information from the **bbox** slot of **counties**.

```{r bbox}
counties@bbox
```

<br />

Using this information, we define the geographic coordinate of the lower left corner of the gridded layer and its number of rows and columns. We then feed these information into the **GridTopology( )** function to create a SpatialGridDataFrame consisting of 0.25- by 0.25- mile grids.

```{r grids}
#--- latitude ---#
left_lon <- counties@bbox[1,1]-0.01
num_col <- ceiling((counties@bbox[1,2]-left_lon)/lat_step_size)

#--- longitude ---#
down_lat <- counties@bbox[2,1]-0.01
num_row <- ceiling((counties@bbox[2,2]-down_lat)/lon_step_size)

#--- create SpatialGridDataFrame ---#
gt <- GridTopology(c(left_lon,down_lat),c(lon_step_size,lat_step_size),c(num_row,num_col))
spg <- SpatialGrid(gt)
ny_grids <- SpatialGridDataFrame(spg, data.table(id = 1:(num_col*num_row)))
```

<br />

Now, let's import fake property location data that I created. We then use the **coordinates( )** function to transform the data into a SpatialPointsDataFrame.

```{r prop}
prop <- fread('fake_poperty.csv')
head(prop)
coordinates(prop) <- c('lon','lat')
prop
```

<br />

To identify which property falls within which grid cell in the gridded layer created above, we use the **over( )** function. 

```{r over}
which_poly <- over(prop,ny_grids) %>% data.table()
which_poly <- cbind(prop@data$prop_id,which_poly)
setnames(which_poly,names(which_poly),c('pid','grid_id'))
which_poly
```

<br />

You can see that each property is assigned a unique grid id value. Now you can use this information to create grid dummies or grid-year dummies to implement estimation similar to those done in @linn13.

<br />
<br />

## Session Information

---------------

```{r session, echo=FALSE}
sessionInfo()
```

<br />
<br />

## References

---------------

<p><span id="linn13">Linn, J. (2013). The effect of voluntary brownfields programs on nearby property values: Evidence from Illinois. <i>Journal Of Urban Economics</i>, <i>78</i>, 1–18.</span></p>

